export const CONFIGURATION_ERROR_CODES = {
  // General Configuration Errors
  CFG_1001: "MISSING_CONFIG",
  CFG_1002: "INVALID_CONFIG_SYNTAX",
  CFG_1003: "INVALID_ENV_VAR",
  CFG_1004: "CONFIG_VALIDATION_FAILED",
  CFG_1005: "INVALID_APP_SETTINGS",

  // Mongoose Schema Builder Errors
  CFG_2001: "INVALID_MODEL_NAME",
  CFG_2002: "INVALID_CONFIG_STRUCTURE",
  CFG_2003: "MISSING_SCHEMA_FIELDS",
  CFG_2004: "INVALID_FIELDS_STRUCTURE",
};
