export const CONFIGURATION_ERROR_CODES = {
  CFG_1001: "MISSING_CONFIG",
  CFG_1002: "INVALID_CONFIG_SYNTAX",
  CFG_1003: "INVALID_ENV_VAR",
  CFG_1004: "CONFIG_VALIDATION_FAILED",
  CFG_1005: "INVALID_APP_SETTINGS",
};
