export const SYSTEM_ERROR_CODES = {
  SYS_1001: "SYSTEM_ERROR",
  SYS_1002: "RESOURCE_EXHAUSTED",
  SYS_1003: "PROCESS_CRASH",
  SYS_1004: "MEMORY_LIMIT_EXCEEDED",
  SYS_1005: "UNHANDLED_REJECTION",
  SYS_1006: "UNCAUGHT_EXCEPTION",
};
